# Generated by Django 4.2 on 2023-04-21 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='register_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emp_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_fullname', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_companyname', models.CharField(max_length=100)),
                ('emp_role', models.CharField(max_length=100)),
                ('emp_domain', models.CharField(max_length=100)),
                ('emp_location', models.CharField(max_length=100)),
                ('emp_status', models.BooleanField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='TestApp.company_db')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
